import Yup from './validation'

export const ApplicationFormSchema = Yup.object().shape({
  applicationForm: Yup.object().shape({
    name: Yup.string().required(),
    surname: Yup.string().required(),
    birthday: Yup.date().required(),
    birthPlace: Yup.string(),
    provincesId: Yup.string().required(),
    districtId: Yup.string().required(),
    nationalityId: Yup.string().oneOf(['1', '2', '3', '4']).nullable(),
    dualNationality: Yup.bool(),
    genderId: Yup.string().oneOf(['1', '2', '3']).nullable(),
    ageRangeId: Yup.string().oneOf(['1', '2', '3', '4']).nullable(),
    phone: Yup.string().required(),
    email: Yup.string().required(),
    graduationId: Yup.string().oneOf(['1', '2', '3', '4', '5', '6', '7', '8']).nullable(),
    germanLevelId: Yup.string().oneOf(['1', '2', '3', '4', '5', '6', '7']).nullable(),
    drivingLicense: Yup.bool(),
    balanceId: Yup.string().oneOf(['1', '2', '3']).required(),
    passport: Yup.bool(),
    length: Yup.string(),
    weight: Yup.string(),
    disabilityStatus: Yup.string(),
    chronicDisease: Yup.string(),
    emergencyPersonFullName: Yup.string(),
    emergencyPersonPhone: Yup.string(),
    emergencyPersonEmail: Yup.string(),
    emergencyPersonDegreeOfProximity: Yup.string(),
    appSelectedLanguages: Yup.array().nullable(),
    categoryId: Yup.string().required(),
    categoryName: Yup.string().when('categoryId', {
      is: '37',
      then: Yup.string().required('Başvurduğunun alanın adını giriniz'),
    }),
  }),
})
